

export enum MessageType{
    SUCCESS= "SUCCESS",
    FAILURE= "FAILURE",
    OFFER = "OFFER",
    ANSWER = "ANSWER",
    MATCHED = "MATCHED"
    
}
export enum ErrorType{
NON_JSON_FORMAT="NON_JSON_FORMAT",
INVALID_PAYLOAD="INVALID_PAYLOAD",
SENDER_UNIDENTIFIED = "SENDER_UNIDENTIFIED",
RECIEVER_UNIDENTIFIED = "RECIEVER_UNIDENTIFIED",
NO_USERS = "NO_USERS",
NO_MATCH_FOUND = "NO_MATCH_FOUND"
}

export enum RequestType{
    SKIP="SKIP",
    SET_SENDER = "SET_SENDER",
    SET_RECIEVER = "SET_RECIEVER",
    OFFER = "OFFER",
    ANSWER = "ANSWER",
    ADD_ICE_CANDIDATES = "ADD_ICE_CANDIDATES",
    FIND_NEXT = "FIND_NEXT",
    STOP = "STOP"
}



